

ALTER PROCEDURE spJobs_DeleteJob(	
	@Id INT
)

AS 
BEGIN
	
	SET NOCOUNT ON

	BEGIN TRY
		BEGIN TRANSACTION DelJob
			UPDATE dbo.Job
			SET Active = 0
			WHERE Id = @Id
		COMMIT TRANSACTION DelJob
	END TRY

	BEGIN CATCH
		
		IF @@TRANCOUNT >0
			ROLLBACK TRANSACTION

		SELECT ERROR_MESSAGE() AS [Error Message]
				 ,ERROR_LINE() AS ErrorLine
				 ,ERROR_NUMBER() AS [Error Number]  
				 ,ERROR_SEVERITY() AS [Error Severity]  
				 ,ERROR_STATE() AS [Error State]  
	END CATCH

	SET NOCOUNT OFF
END